Repository icure/medtech-docs, pull requests merged in 2022-11, with the labels that each got.

#15 How to Create a User for an Existing Patient
  code-samples/explanation/data-sample-w-coding/index.mts
  code-samples/explanation/doctor-creates-he/index.mts
  code-samples/explanation/doctor-invites-a-patient/index.mts
  code-samples/explanation/doctor-shares-data-with-patient/index.mts
  code-samples/explanation/patient-creates-data-sample/index.mts
  code-samples/how-to/create-user-for-patient/index.mts
  code-samples/how-to/datasamples/index.mts
  code-samples/how-to/hierarchical-datasample/index.mts
  code-samples/how-to/patients/index.mts
  code-samples/utils/endpoint.mts
  docusaurus.config.js
  sdks/explanations/data-model/data-model-medical-device.md
  sdks/explanations/data-model/data-model-notification.md
  sdks/explanations/data-model/data-model-patient.md
  sdks/how-to/how-to-create-a-user-from-a-patient.md
  sdks/how-to/how-to-manage-patients.md
Labels: documentation

#17 How to/manage notifications
  code-samples/how-to/manage-notifications/index.mts
  code-samples/utils/endpoint.mts
  sdks/how-to/how-to-manage-notifications.md
Labels: enhancement

#19 How to Migrate to iCure Premium Features
  code-samples/how-to/migrate-to-premium/index.mts
  code-samples/utils/initialization.mts
  sdks/explanations/data-model/data-model-healthcare-professional.md
  sdks/explanations/data-model/data-model-notification.md
  sdks/how-to/how-to-auto-share-data.md
  sdks/how-to/how-to-create-a-user-from-a-patient.md
  sdks/how-to/how-to-manage-notifications.md
  sdks/how-to/how-to-migrate-to-icure-premium-features.md
  sdks/how-to/how-to-share-data.md
Labels: documentation

#13 How to Authenticate user
  code-samples/how-to/authenticate-user-by-sms/index.mts
  code-samples/how-to/authenticate-user/index.mts
  code-samples/how-to/auto-share/index.mts
  code-samples/how-to/sharing-data/index.mts
  code-samples/package.json
  code-samples/utils/initialization.mts
  code-samples/utils/msgGtw.mts
  sdks/how-to/how-to-authenticate-a-user/index.md
  sdks/how-to/how-to-authenticate-a-user/my-user-authenticates-by-sms.md
  sdks/how-to/how-to-authenticate-a-user/my-user-lost-their-key.md
  sdks/how-to/how-to-create-a-user-from-a-patient.md
  sdks/how-to/how-to-listen-to-icure-events.md
  sdks/how-to/how-to-login-as-a-user.md
  sdks/how-to/how-to-register-a-user.md
  sdks/tutorial/index.md
Labels: documentation

#23 How to manage hcps
  code-samples/.eslintrc
  code-samples/how-to/manage-healthcare-professionals/index.mts
  code-samples/package.json
  code-samples/utils/initialization.mts
  sdks/glossary.md
  sdks/how-to/how-to-manage-healthcare-professionals.md
  sdks/how-to/how-to-share-data-automatically.md
  sdks/how-to/how-to-share-data.md
Labels: documentation

#26 Added auto-generated release-notes
  package.json
  sdks/release-notes.mdx
  sidebarsSDK.js
  src/components/ReleaseNotes/ReleaseNotes.tsx
  yarn.lock
Labels: documentation, enhancement

#27 Updated Docusaurus to 2.2.0
  docusaurus.config.js
  package.json
  yarn.lock
Labels: enhancement
