Repository icure/medtech-docs, pull requests merged in 2023-03, with the labels that each got.

#34 Updated docusaurus du 2.4.0
  package.json
  yarn.lock
Labels: enhancement

#36 Updated medtech version
  code-samples/explanation/doctor-creates-he/index.mts
  code-samples/explanation/doctor-invites-a-patient/index.mts
  code-samples/how-to/authenticate-user-by-sms/index.mts
  code-samples/how-to/authenticate-user/index.mts
  code-samples/how-to/auto-share/index.mts
  code-samples/how-to/create-user-for-patient/index.mts
  code-samples/how-to/datasamples/index.mts
  code-samples/how-to/hierarchical-datasample/index.mts
  code-samples/how-to/manage-healthcare-elements/index.mts
  code-samples/how-to/manage-healthcare-professionals/index.mts
  code-samples/how-to/migrate-to-premium/index.mts
  code-samples/how-to/patients/index.mts
  code-samples/how-to/rsocket/index.mts
  code-samples/how-to/sharing-data/index.mts
  code-samples/how-to/use-complex-search-criteria/index.mts
  code-samples/package.json
  code-samples/runall.mts
  code-samples/tutorial/doctor-centric-app/index.mts
  code-samples/yarn.lock
  sdks/how-to/how-to-filter-data-with-advanced-search-criteria.md
Labels: enhancement

#41 Added troubleshooting page
  code-samples/how-to/patients/index.mts
  sdks/glossary.md
  sdks/how-to/how-to-use-to-icure-premium-features.md
  sdks/troubleshooting.md
  sidebarsSDK.js
Labels: enhancement

#48 Added Agolia DocSearch
  docusaurus.config.js
  package.json
  yarn.lock
Labels: documentation, enhancement

#47 Added documentation about API instantiation
  code-samples-watch/watch.mts
  code-samples/how-to/how-to-use-with-redux/index.mts
  code-samples/how-to/instantiate-the-medtech-sdk/index.mts
  code-samples/how-to/patients/index.mts
  sdks/explanations/data-model/data-model-coding.md
  sdks/explanations/data-model/data-model-data-sample.md
  sdks/explanations/data-model/data-model-healthcare-element.md
  sdks/explanations/data-model/data-model-healthcare-professional.md
  sdks/explanations/data-model/data-model-patient.md
  sdks/how-to/how-to-authenticate-a-user/index.md
  sdks/how-to/how-to-authenticate-a-user/my-user-authenticates-by-sms.md
  sdks/how-to/how-to-authenticate-a-user/my-user-lost-their-key.md
  sdks/how-to/how-to-create-a-user-from-a-patient.md
  sdks/how-to/how-to-filter-data-with-advanced-search-criteria.md
  sdks/how-to/how-to-instantiate-the-medtech-sdk.md
  sdks/how-to/how-to-manage-data-samples/how-to-manage-datasamples-with-hierarchical-information.md
  sdks/how-to/how-to-manage-data-samples/index.md
  sdks/how-to/how-to-manage-healthcare-elements.md
  sdks/how-to/how-to-manage-healthcare-professionals.md
  sdks/how-to/how-to-manage-notifications.md
  sdks/how-to/how-to-manage-patients.md
  sdks/how-to/how-to-manage-users.md
  sdks/how-to/how-to-share-data-automatically.md
  sdks/how-to/how-to-subscribe-to-icure-events.md
  sdks/how-to/how-to-use-with-redux.md
  sdks/tutorial/index.md
Labels: documentation
